// <auto-generated />
using DugoviLG_PIN.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DugoviLG_PIN.Migrations.PotDugovi
{
    [DbContext(typeof(PotDugoviContext))]
    [Migration("20180127164445_MyMig1")]
    partial class MyMig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DugoviLG_PIN.Models.PotDugovi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ime");

                    b.Property<string>("KontaktBroj");

                    b.Property<string>("Prezime");

                    b.HasKey("ID");

                    b.ToTable("PotDugovi");
                });
#pragma warning restore 612, 618
        }
    }
}
